#!/bin/bash

# Get the top level of the git-repo
head=`git rev-parse --show-toplevel`

# Go to the top of the git-repo
pushd $head

for f in .hooks/*
do
    bf=$(basename $f)
    chmod u+x $f
    ln -sf $head/$f $head/.git/hooks/$bf
    ls -l $head/.git/hooks/$bf
done

popd
