#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Redirect output to stderr.
exec 1>&2

version=`git describe --always --tag`
echo "Fixing version for smeka ($version)"

sed -i -e "s/^\(SMEKA_VERSION\).*/\1 = $version/" make/smeka/Makefile.smeka 
retval=$?
if [ $retval -ne 0 ]; then
    echo "Could not insert the smeka-version"
    retval=1
fi

exit $retval


