_SMEKA_project = 1

# Contains specific default information for this
# project

# Step this version upon new versions
PROJECT_VERSION = %%VERSION%%

# These are constant default
PROJECT_NAME = %%PROJECT%%


# Local Variables:
#  mode: makefile-gmake
# End:
