#
# smeka Makefile setup
#
#
# This Makefile was created by smeka:
#  github.com/zerothi/smeka


# The top-directory of the Makefile/source tree
# It *MUST* be the directory where the Makefile
# is located.
TOP_DIR ?= .

# This is the directory where the smeka
# generic files are stored (default to smeka)
SMEKA_DIR = smeka

# Include the smeka settings!
include $(TOP_DIR)/$(SMEKA_DIR)/Makefile.smeka


