_SMEKA_dist = 1
.PHONY: dist

# This distribution forces the creation of the
# pre-processed sources.
# This makes the sources available for the
# distribution tarball.
dist:: $(CPP_SOURCES)

# Local Variables:
#  mode: makefile-gmake
# End:
